apiVersion: v2
name: chart-base
description: Base chart with Deployment, Service, ConfigMaps and ExternalSecret
type: application

# generada automaticamente por release-please a partir de Conventional Commits.
version: 0.1.0

# NO gestionada por release-please: Helm la trata como independiente de la version
# del chart (puedes cambiar el chart sin recompilar la app).
appVersion: "1.0.0"